### ISSUE TITLE
Change slide based on external controls

### ISSUE THREAD

**Issue by shanejones** [jiangbo2015/framer-motion-carousel#10]
Hi, Love this plugin. Found it after searching for how to make a carousel in framer motion and you've saved me quite a bit of time here :) 

I was wondering if there was a way to control it via an external control. I have some buttons elsewhere on my page that I need to  control this section. Assuming I should be able to do this by passing the key into the component somehow

Do you know if this is possible?

Thanks!

**Comment by jiangbo2015** [comment]
2.0.3 released
