### ISSUE TITLE
Disable draggable feature

### ISSUE THREAD

**Issue by arturzhilindev** [jiangbo2015/framer-motion-carousel#2]
How I can disable the draggable feature for slides (if slides are DIVs, not images)? So I can change a slide only by using arrows. 
Thanks.

**Comment by jiangbo2015** [comment]
Can you tell me why you want to draggable feature?

we use motion.div to wrap every custom slide, the drag="x" is default set to enable drag.
I think enabling draggable is a good experience.

```jsx
<motion.div
        style={{
            ...pageStyle,
            x,
            left: `${i * 100}%`,
            right: `${i * 100}%`,
        }}
        drag="x"
        dragElastic={0.3}
        onDragEnd={onDragEnd}
    >
        {children}
    </motion.div>
```

**Comment by AshMW2724** [comment]
It would be nice to disable drag via a prop due to this still being in issue:
![GIF showing draging more to an end while on the list slide with loop disabled](https://legal-loli.art/AMsfEZgJka.gif)
