### ISSUE TITLE
Arrows are not centered

### ISSUE THREAD

**Issue by miguelmigs24** [jiangbo2015/framer-motion-carousel#3]
The navigation arrows are not vertically centered inside the circle

**Comment by jiangbo2015** [comment]
I use flex center it
```
    ...
    display: flex;
    align-items: center;
    justify-content: center;
```

![image](https://user-images.githubusercontent.com/14797518/145992837-8fd81250-214d-4370-a9ac-6ada36fa75ab.png)

**Comment by jiangbo2015** [comment]
closed
