### ISSUE TITLE
Hiding control elements

### ISSUE THREAD

**Issue by lewis-kori** [jiangbo2015/framer-motion-carousel#7]
Hi. Love the library.
Is there a way to hide the arrow icons and dots?

**Comment by hfg-joschua-r** [comment]
+1

**Comment by jiangbo2015** [comment]
Use custom rendering, and return null
```
<Carousel renderArrowLeft={() => null} renderArrowRight={() => null} renderDots={() => null}>
```

**Comment by lewis-kori** [comment]
> Use custom rendering, and return null
> 
> ```
> <Carousel renderArrowLeft={() => null} renderArrowRight={() => null} renderDots={() => null}>
> ```

Thanks!
