### ISSUE TITLE
Fix unmounting typo

### ISSUE THREAD

**Issue by Littletonconnor** [jiangbo2015/framer-motion-carousel#8]
Hi, love how easy this lib is to get started with!

One thing I noticed while using this is there's a typo when un-mounting inside `carousel.tsx`.

```tsx
    React.useEffect(() => {
        const controls = animate(x, calculateNewX(), transition)
        return controls.stop // This should be controls.stop()
    }, [index])
```

**Comment by Littletonconnor** [comment]
Happy to quickly fix this if you guys want me to :)

**Comment by jiangbo2015** [comment]
`useEffect` need to return a function, so `return controls.stop` without `()`.
Or another way `return () => controls.stop()` with `()`
