### ISSUE TITLE
Custom Arrow left, rigth and dots not working

### ISSUE THREAD

**Issue by kaname-png** [jiangbo2015/framer-motion-carousel#9]
When the component is used in this way, the controls disappear, and the custom control is not displayed.

```tsx
<Carousel
				autoPlay={false}
				interval={5000}
				loop={false}
				renderDots={() => null}
				renderArrowLeft={({ handlePrev }) => <IconButton onClick={handlePrev} icon={<ArrowLeft />} aria-label={'Prev review'} />}
				renderArrowRight={({ handleNext }) => <IconButton onClick={handleNext} icon={<ArrowRight />} aria-label={'Prev review'} />}
			>
				....
			</Carousel>
```

> Without custom controls

![image](https://user-images.githubusercontent.com/56084970/203472703-d7ede964-e2a9-472a-a873-78e998b2c68e.png)

> With custom controls

![image](https://user-images.githubusercontent.com/56084970/203472727-5ad5f5db-0acf-42ed-953a-0bb70d04c077.png)

**Comment by kaname-png** [comment]
I also tried using the native html button and it didn't work.

**Comment by jiangbo2015** [comment]
you need set custom style to your component, see example blow

[codesanbox](https://codesandbox.io/s/affectionate-browser-pdfn0v?file=/src/index.tsx)
